language: node_js
node_js:
  - "node"
script: npm run lint
repo: "https://github.com/dartmouth-cs98/project-dartmap"
deploy:
  provider: surge
  project: ./
  skip_cleanup: true
before_deploy: npm run build
